spring.application.name=worker
server.port=8084


# ============================================
# Database
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gajraj_paithani_workers
spring.datasource.username=postgres
spring.datasource.password=root


# ============================================
# Hibernate / JPA
# ============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ============================================
# Security Config
# ============================================
server.servlet.session.cookie.same-site=STRICT
spring.main.web-application-type=SERVLET
spring.security.user.name=""
spring.security.user.password=""


# ============================================
# JWT Keys and Ex
# ============================================
jwt.public-key=classpath:keystore/public.pem
jwt.expiration=900000
