spring.application.name=shipping
server.port=8089


# ============================================
# Database
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gajraj_paithani_shipping
spring.datasource.username=postgres
spring.datasource.password=root


# ============================================
# Hibernate / JPA
# ============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ============================================
# JWT
# ============================================
jwt.public-key=classpath:keys/public.pem


# ============================================
# Security Config
# ============================================
server.servlet.session.cookie.same-site=STRICT
spring.main.web-application-type=SERVLET
spring.security.user.name=""
spring.security.user.password=""


# ============================================
# Eureka Service Discovery
# ============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
