spring.application.name=payment
server.port=8088


# ============================================
# Database
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gajraj_paithani_payments
spring.datasource.username=postgres
spring.datasource.password=root



# ============================================
# Hibernate / JPA
# ============================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ============================================
# Security Config
# ============================================
server.servlet.session.cookie.same-site=STRICT
spring.main.web-application-type=SERVLET
spring.security.user.name=""
spring.security.user.password=""


# ============================================
# Razorpay
# ============================================
razorpay.key.id=rzp_test_T91I6qhyUtG98t
razorpay.key.secret=WpDYb0DDJM1IsG3o9qP76lK1