name: Build and Test Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build authentication image
        run: docker build -t authentication:test ./authentication

      - name: Build customer image
        run: docker build -t customer:test ./customer

      - name: Build Customer Frontend Side Image
        run: docker build -t customerfrontend:test ./front-end/customer-frontend
